- name: Install python version
  package:
    name: "rh-python{{ scl_python_version }}"
    state: present
  become: true

- name: Globally enable scl python
  lineinfile:
    path: /etc/profile.d/scl-python.sh
    line: "source /opt/rh/rh-python{{ scl_python_version }}/enable"
    create: yes
  become: true

